services:
  backend:
    build:
      context: ./books_lab_backend
    ports:
      - "8081:8081"
    depends_on:
      - db
      
  frontend:
    build:
      context: ./books_lab_frontend/books_lab_frontend
    ports:
      - "3000:80"

  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: emt_books
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./books_lab_backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./books_lab_backend/views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - 2345:5432
volumes:
  pgdata:
