
CREATE TABLE country (
                         id bigint generated by default as identity primary key,
                         name VARCHAR(255) NOT NULL,
                         continent VARCHAR(255) NOT NULL
);

CREATE TABLE author (
                        id bigint generated by default as identity primary key,
                        name VARCHAR(255) NOT NULL,
                        surname VARCHAR(255) NOT NULL,
                        country_id BIGINT REFERENCES country(id)
);


CREATE TABLE book (
                      id bigint generated by default as identity primary key,
                      name VARCHAR(255) NOT NULL,
                      category VARCHAR(50),
                      author_id BIGINT REFERENCES author(id),
                      is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE book_copy (
                           id bigint generated by default as identity primary key,
                           book_id BIGINT REFERENCES book(id) on delete cascade,
                           is_available BOOLEAN DEFAULT TRUE,
                           state VARCHAR(255)
);

CREATE TABLE shop_users (
                            username VARCHAR(255) primary key,
                            password VARCHAR(255) NOT NULL,
                            name VARCHAR(255),
                            surname VARCHAR(255),
                            is_account_non_expired BOOLEAN DEFAULT TRUE,
                            is_account_non_locked BOOLEAN DEFAULT TRUE,
                            is_credentials_non_expired BOOLEAN DEFAULT TRUE,
                            is_enabled BOOLEAN DEFAULT TRUE,
                            role VARCHAR(50)
);


CREATE TABLE shop_users_book_list
(
    shop_users_username VARCHAR(255) REFERENCES shop_users (username),
    book_list_id        BIGINT REFERENCES book (id),
    PRIMARY KEY (shop_users_username, book_list_id)
);